version: '3.1'

services:

  postgres:
    image: postgres:15.0
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER:     buenavida-user
      POSTGRES_DB:       buenavida
      PGDATA:            /var/lib/postgresql/data
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data
    ports:
      - 5432:5432

  mongo:
    image: mongo:4.4.17
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

