version: '3.1'

services:

  mongo:
    image: mongo:4.4.17
    restart: "no"
    volumes:
      - ../data/mongodb:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: buenavida

  mongo-script:
    image: mongo:4.4.17
    restart: "no"
    volumes:
      - ../data/json:/data/json
      - ../util/mongoimport.sh:/opt/mongoimport.sh
    environment:
      MONGO_HOST: mongo
      MONGO_USER: root
      MONGO_PASS: example
    depends_on:
      - "mongo"
    command:
      - /opt/mongoimport.sh
